name: MySQL CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: rootpassword

    steps:
      - uses: actions/checkout@v2
      - name: Run MySQL scripts
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
        run: |
          sudo apt-get install mysql-client
          mysql -h 127.0.0.1 -u root -prootpassword -e "source sql/create_tables.sql"
          mysql -h 127.0.0.1 -u root -prootpassword -e "source sql/insert_data.sql"
          mysql -h 127.0.0.1 -u root -prootpassword -e "source sql/queries.sql"
